#pragma once
// Renames the Vulkan PyroWave C API before <pyrowave.h> is included.
// The Metal static library exports the same identifiers with a different ABI.
// The shim dylib defines the twilight_vkpw_* entry points and calls the real ones.

#define pyrowave_get_api_version twilight_vkpw_pyrowave_get_api_version
#define pyrowave_create_default_device twilight_vkpw_pyrowave_create_default_device
#define pyrowave_create_device twilight_vkpw_pyrowave_create_device
#define pyrowave_create_device_by_compat twilight_vkpw_pyrowave_create_device_by_compat
#define pyrowave_device_report_performance_stats twilight_vkpw_pyrowave_device_report_performance_stats
#define pyrowave_device_get_vk_device_handles twilight_vkpw_pyrowave_device_get_vk_device_handles
#define pyrowave_device_set_command_buffer twilight_vkpw_pyrowave_device_set_command_buffer
#define pyrowave_device_set_queue_type twilight_vkpw_pyrowave_device_set_queue_type
#define pyrowave_device_confirm_interop_support twilight_vkpw_pyrowave_device_confirm_interop_support
#define pyrowave_device_destroy twilight_vkpw_pyrowave_device_destroy
#define pyrowave_sync_object_create twilight_vkpw_pyrowave_sync_object_create
#define pyrowave_sync_object_get_semaphore twilight_vkpw_pyrowave_sync_object_get_semaphore
#define pyrowave_sync_object_export_handle twilight_vkpw_pyrowave_sync_object_export_handle
#define pyrowave_sync_object_cpu_wait twilight_vkpw_pyrowave_sync_object_cpu_wait
#define pyrowave_sync_object_cpu_signal twilight_vkpw_pyrowave_sync_object_cpu_signal
#define pyrowave_sync_object_destroy twilight_vkpw_pyrowave_sync_object_destroy
#define pyrowave_image_create twilight_vkpw_pyrowave_image_create
#define pyrowave_image_get_handle twilight_vkpw_pyrowave_image_get_handle
#define pyrowave_image_get_image_view twilight_vkpw_pyrowave_image_get_image_view
#define pyrowave_image_destroy twilight_vkpw_pyrowave_image_destroy
#define pyrowave_encoder_create twilight_vkpw_pyrowave_encoder_create
#define pyrowave_encoder_encode_gpu_synchronous twilight_vkpw_pyrowave_encoder_encode_gpu_synchronous
#define pyrowave_encoder_encode_cpu_synchronous twilight_vkpw_pyrowave_encoder_encode_cpu_synchronous
#define pyrowave_encoder_compute_num_packets twilight_vkpw_pyrowave_encoder_compute_num_packets
#define pyrowave_encoder_packetize twilight_vkpw_pyrowave_encoder_packetize
#define pyrowave_encoder_destroy twilight_vkpw_pyrowave_encoder_destroy
#define pyrowave_decoder_device_prefers_fragment_path twilight_vkpw_pyrowave_decoder_device_prefers_fragment_path
#define pyrowave_decoder_create twilight_vkpw_pyrowave_decoder_create
#define pyrowave_decoder_clear twilight_vkpw_pyrowave_decoder_clear
#define pyrowave_decoder_push_packet twilight_vkpw_pyrowave_decoder_push_packet
#define pyrowave_decoder_decode_is_ready twilight_vkpw_pyrowave_decoder_decode_is_ready
#define pyrowave_decoder_decode_gpu_buffer twilight_vkpw_pyrowave_decoder_decode_gpu_buffer
#define pyrowave_decoder_decode_cpu_buffer_synchronous twilight_vkpw_pyrowave_decoder_decode_cpu_buffer_synchronous
#define pyrowave_decoder_destroy twilight_vkpw_pyrowave_decoder_destroy
